### ISSUE TITLE
Error handling when path doesn't exist

### ISSUE THREAD

**Issue by vries294** [fguchelaar/FileSystemActions#2]
Path = \Server\dir\NonExisting

A non-existing path results in a crash, an error message in terms of "The path %path% doesn't exist" would be  appropriate.

**Comment by fguchelaar** [comment]
Valid point. I can see two scenarios to fixing this issue:
1) Show error message and exit
2) Show error message, but keep running for other configured watchers?

I would prefer scenario 1. Agree?

**Comment by vries294** [comment]
Yes, agree!
